Feat/background rwd
pycontw/pycontw-frontend pull request #220
Opened 2022-04-18 09:08 UTC by furecool

## Types of changes

* **Update background image & RWD system**

## Description

Set RWD-related class in tailwind.config.js, and use in PageWrapper.vue.
Import images into PageWrapper.vue as background.

## Steps to Test This Pull Request

1. Set RWD-related class in tailwind.config.js. Include extend and screens in theme.
2. In PageWrapper.vue, add  those classes in classObject() ,whitch is a method binding to the div as a class.
3. Add images to '@/static/img/background'.
4. Import images from '@/static/img/background' into PageWrapper.vue.
5. Binding those images as background style
6. In css, set max width that background-image don't display.

## Expected behavior

Add background images , and update RWD system.

## Related Issue

#207 , #208 

## Additional context

2022-04-30 10:20 UTC, flynnhou commented on tailwind.config.js
> +            },
If we're already using [arbitrary value support](https://v2.tailwindcss.com/docs/just-in-time-mode#arbitrary-value-support), do we still need to specify the values in the config?
It looks redundant to me.

2022-04-30 10:41 UTC, flynnhou requested changes
The implementation in `PageWrapper.vue` is fundamentally not idiomatic regarding CSS and TailwindCSS.

## Problems

1. The inline [`backgroundStyle`](https://github.com/pycontw/pycontw-frontend/blob/90105f0693093a7bd8abc540518b61c95ff876ea/components/core/i18n/PageWrapper.vue#L28) made it difficult to toggle the `background-image` on different screen sizes.
2. Hence, the unideal [`!important`](https://github.com/pycontw/pycontw-frontend/blob/90105f0693093a7bd8abc540518b61c95ff876ea/components/core/i18n/PageWrapper.vue#L92) is introduced to override the inline style because of [CSS specificity](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity).

## Suggestions

Extend tailwind config with the custom background rules:

###### tailwind.config.js

```js
module.exports = {
    ...
    theme: {
        extend: {
            backgroundImage: {
                wrapper:
                    'url("~/static/img/background/l1.svg"), url("~/static/img/background/l2.svg"), url("~/static/img/background/l3.svg"), url("~/static/img/background/r1.svg"), url("~/static/img/background/r2.svg"), url("~/static/img/background/r3.svg"), url("~/static/img/background/l1.svg"), url("~/static/img/background/l2.svg"), url("~/static/img/background/l3.svg"), url("~/static/img/background/r1.svg"), url("~/static/img/background/r2.svg"), url("~/static/img/background/r3.svg")',
            },
            backgroundPosition: {
                'wrapper-top-left':
                    '4% 100px, 4% 958px, 4% 1816px, 96% 200px, 96% 1058px, 96% 1916px, 4% 2674px, 4% 3532px, 4% 4390px, 96% 2774px, 96% 3632px, 96% 4490px',
            },
        },
    },
    ...
}
```

This way, we can utilize Tailwind's syntax sugar to deal with the background-image on different screen sizes:

###### components/core/i18n/PageWrapper.vue

```vue
<template>
    <div class="page-wrapper">
        <div :class="classObject">
            <slot></slot>
        </div>
    </div>
</template>

<script>
export default {
  // don't need `backgroundStyle()` anymore
  // only the `classObject()` updates are needed
}
</script>

<style lang="postcss" scoped>
...
.page-wrapper {
    @apply bg-none lg:bg-wrapper bg-no-repeat bg-wrapper-top-left;
}
</style>
```

2022-04-30 10:45 UTC, flynnhou commented
@furecool Please take a look and let me know if the code review makes sense to you!

2022-04-30 15:40 UTC, furecool commented
> @furecool Please take a look and let me know if the code review makes sense to you!

You are right, thanks!

2022-05-08 11:31 UTC, furecool commented on components/core/i18n/PageWrapper.vue
> -        customX: { type: Boolean, default: false },
Already add this back， thanks!

2022-05-08 11:50 UTC, flynnhou commented on components/core/i18n/PageWrapper.vue
> -        customX: { type: Boolean, default: false },
@furecool Please fix the lint error QQ https://github.com/pycontw/pycontw-frontend/runs/6340634307?check_suite_focus=true#step:6:14

2022-05-08 12:04 UTC, furecool commented on components/core/i18n/PageWrapper.vue
> -        customX: { type: Boolean, default: false },
sorry, alreary fix it .

2022-05-08 12:28 UTC, flynnhou approved these changes
lgtm! @furecool thank you!

2022-05-08 12:30 UTC, merged