feat(info-section): add info-section layout to home page
pycontw/pycontw-frontend pull request #233
Opened 2022-04-28 14:19 UTC by Wizardgreen

## Types of changes

* **New feature**

## Description

Create Info-section for Home page.

2022-04-28 15:48 UTC, mattwang44 commented on components/core/layout/TwoColWrapper.vue
> +            <slot name="left-col"></slot>
This is not relevant to the PR and do break the other page (`2022/<lang>/registration/financial-aid`). Please revert the change.

2022-04-28 16:23 UTC, mattwang44 requested changes
Since we implemented [a component](https://github.com/pycontw/pycontw-frontend/tree/main/components/intro) for this section last year, if you want to do it from scratch (though not recommended), please delete the old version.

2022-04-28 16:23 UTC, mattwang44 commented on pages/index.vue
> +            <div class="info-section section-wrapper">
The mobile layout does not conform to the [design spec](https://www.figma.com/file/W3hdepQ7v7ZGYRP6QctBXH/PyCon-Taiwan-%E5%AE%98%E7%B6%B2%E8%A6%96%E8%A6%BA-2022?node-id=31%3A1821). Please check again.
<img width="501" alt="image" src="https://user-images.githubusercontent.com/24987826/165798403-ec4ac919-9872-46f9-b1bf-f61b8c82d824.png">

2022-05-12 17:03 UTC, mattwang44 commented on components/intro/Intro.vue
> -.intro-milestones-title {
the title should emerge both on web view and mobile view (there is a small error on figma).

2022-05-12 17:07 UTC, mattwang44 commented on components/intro/Intro.i18n.js
> +            'PyCon APAC is the annual gathering of the global Python community. ' +
I'm currently asking for help to revise the translation ([discord link](https://discord.com/channels/752904426057892052/946041922827472897/972428476185448549)).

2022-05-25 19:17 UTC, mattwang44 commented on components/intro/Intro.i18n.js
> +            'PyCon APAC is the annual gathering of the global Python community. ' +
updated
reference: https://discord.com/channels/752904426057892052/946041922827472897/972428476185448549

2022-05-29 17:18 UTC, flynnhou approved these changes
LGTM.

Note that we need to audit the screen breakpoints. We should be able to eliminate media queries by using tailwind's `screens` variants.

2022-05-30 03:29 UTC, merged