fix(banner): revise title style and banner component
pycontw/pycontw-frontend pull request #240
Opened 2022-05-08 10:44 UTC by SivanYeh

## Types of changes

* **Bugfix**
* **New feature**
* **Refactoring**
* **Breaking change** (any change that would cause existing functionality to not work as expected)
* **Documentation Update**
* **Other (please describe)**

## Description

## Steps to Test This Pull Request

## Expected behavior

## Related Issue

## Additional context

2022-06-20 14:11 UTC, flynnhou commented
@SivanYeh Please provide PR description otherwise it is too painful to review.

2022-06-20 14:20 UTC, flynnhou commented
When language is EN, it looks off:

| PR | Figma |
|----|-------|
| <img width="720" alt="image" src="https://user-images.githubusercontent.com/7352613/174621533-059e72c2-5731-461f-b8c3-6d3f3118a335.png"> | <img width="785" alt="image" src="https://user-images.githubusercontent.com/7352613/174622325-0ef1b0f1-5bf4-4108-8540-a419542dd97a.png"> |

2022-06-20 15:15 UTC, flynnhou requested changes
Besides the code, the images aren't as ideal.

1. I don't think we need another `BannerBody.svg` because it seems like the entire app's background color, no?
2. Need to rename `RWD2.png` and `WEB2.png`:
   - Why all uppercase? Rename it to kebab case.
   - RWD2 and WEB2 don't reflect the meaning behind the images. They should be named as something like `banner-mobile.png` and `banner-desktop.png`, respectively.
   - Consider to move them under `static/img/background/`
3. These are background images and are displayed as assets. Their current sizes are too large for their lower significance. See if you can export the images to make them at least less than 1MB, the smaller the better. Image sizes will affect the performance and user experience of the website. If you don't know how to make this happen, leave it as it is for now.

2022-06-20 15:15 UTC, flynnhou commented on components/core/layout/Banner.vue
> +            <slot name="standard"></slot>
Can you explain what's the rationale behind this change?
I'll be providing a better solution to optimize tailwind's rwd soon. In the meantime, see if you can find some clues from this merged PR: https://github.com/pycontw/pycontw-frontend/pull/220.

2022-07-05 15:50 UTC, mattwang44 commented
close this PR as #266 is merged

2022-07-05 15:50 UTC, closed without merging