Young inspirers page
pycontw/pycontw-frontend pull request #263
Opened 2022-06-26 06:10 UTC by SivanYeh

## Types of changes

* **Bugfix**
* **New feature**
* **Refactoring**
* **Breaking change** (any change that would cause existing functionality to not work as expected)
* **Documentation Update**
* **Other (please describe)**

## Description

## Steps to Test This Pull Request

## Expected behavior

## Related Issue

## Additional context

2022-07-02 08:11 UTC, josix reviewed
Thank you @SivanYeh for the hard work, I've updated this page to follow the spec's styling and added the latest information.

2022-07-05 17:50 UTC, mattwang44 requested changes

2022-07-05 17:50 UTC, mattwang44 commented on pages/conference/young-inspirers.vue
> +            tagToLangIcon: {
the style of icons should conform to the spec (may need designer's help for the zh icon)

<img width="1120" alt="image" src="https://user-images.githubusercontent.com/24987826/177385474-99141353-b2d0-42ae-a278-07b9c67c6c38.png">

2022-07-05 17:50 UTC, mattwang44 commented on pages/conference/young-inspirers.vue
> +                                    >
```suggestion
                                    <text-button
                                        :href="speech.live_link"
                                        small
                                        class="linkButton"
                                    >
                                        觀看直播
                                    </text-button>
                                    <text-button
                                        :href="speech.note_link"
                                        secondary
                                        large
                                        class="linkButton"
                                    >
```

2022-07-05 17:55 UTC, mattwang44 commented on i18n/conference/young-inspirers.i18n.js
> +                        title: 'Comeing S',
typo?

2022-07-08 10:36 UTC, mattwang44 requested changes
Mobile view issues

2022-07-08 10:36 UTC, mattwang44 commented on pages/conference/young-inspirers.vue
> +                                    {{ speech.full_description }}
The description should be truncated if it's too long. The following is the snapshot of figma.

<img width="344" alt="image" src="https://user-images.githubusercontent.com/24987826/177976295-1bebc876-e276-491d-a684-3b57a05b0f3d.png">

2022-07-09 09:28 UTC, mattwang44 commented on pages/conference/young-inspirers.vue
> +                                    {{ speech.full_description }}
spec deleted

2022-07-10 09:25 UTC, mattwang44 approved these changes
I've rebased the branch and roughly cleaned up the commit history.
Please open another PR for following issues (if any).

2022-07-10 09:26 UTC, merged