feat(about/index): revamp style of about/index page
pycontw/pycontw-frontend pull request #273
Opened 2022-07-10 11:27 UTC by josix

## Types of changes

* **New feature**

## Description
Update styling of the about index page following the spec. 

## Steps to Test This Pull Request
Running `npm run dev` and checkout `http://localhost:3000/2022/zh-hant/about/`

## Expected behavior

<img src="https://user-images.githubusercontent.com/18432820/178142876-cfc2aec7-6356-4ac1-b2a3-60328614b5e1.png" width="300" />

![localhost_3000_2022_zh-hant_about_](https://user-images.githubusercontent.com/18432820/178142879-3b3e673b-83da-4524-abae-26c44d4d8994.png)

2022-07-10 20:05 UTC, mattwang44 requested changes

2022-07-10 20:05 UTC, mattwang44 commented on pages/about/index.vue
> +                            w-32
nit: consider assign a new class and move these lines to CSS block

2022-07-10 20:05 UTC, mattwang44 commented on pages/about/index.vue
> +                class="
ditto

2022-07-10 20:05 UTC, mattwang44 commented on pages/about/index.vue
> +                    lg:text-base
redundant

```suggestion
```

2022-07-10 20:05 UTC, mattwang44 commented on pages/about/index.vue
> +    @apply w-full text-xs md:text-base lg:text-base;
redundant

```suggestion
    @apply w-full text-xs md:text-base;
```

2022-07-10 20:05 UTC, mattwang44 commented on pages/about/index.vue
> +    @apply font-serif text-primary-100 my-3 text-base md:text-lg lg:text-lg font-bold;
redundant
```suggestion
    @apply font-serif text-primary-100 my-3 text-base md:text-lg font-bold;
```

2022-07-11 17:17 UTC, josix commented on pages/about/index.vue
> +                class="
Fixed on 5c1a9f7ddb9bfb30db36f2ecd8cba5f366ffb755

2022-07-12 04:58 UTC, mattwang44 approved these changes
thx for the beautiful work!

2022-07-12 04:58 UTC, merged