Bulletin card
pycontw/pycontw-frontend pull request #275
Opened 2022-07-10 15:57 UTC by tingchun0113

## Types of changes

* **New feature**

## Description

Contribute some bulletin card samples first to the project

## Steps to Test This Pull Request

## Expected behavior

## Related Issue

## Additional context

2022-07-13 08:07 UTC, josix requested changes

2022-07-13 08:07 UTC, josix commented on components/bulletins/BulletinCard.vue
> +    padding: inherit;
```suggestion
```

2022-07-13 08:07 UTC, josix commented on components/bulletins/BulletinCard.vue
> +    font-family: 'Noto Serif TC';
```suggestion
    @apply font-serif;
```

2022-07-16 00:40 UTC, tingchun0113 commented on components/bulletins/BulletinCardCollection.vue
> +    @apply grid place-items-center gap-10 grid-cols-1 mt-9 md:grid-cols-3 md:pl-14 md:mt-0 md:w-10/12;
Fixed

2022-07-16 00:42 UTC, tingchun0113 commented on components/bulletins/BulletinCard.vue
> +    padding: inherit;
Fixed

2022-07-16 00:45 UTC, tingchun0113 commented on components/bulletins/BulletinCard.vue
> +    font-family: 'Noto Serif TC';
Fixed

2022-08-10 16:59 UTC, mattwang44 commented on components/bulletins/BulletinCard.vue
> +        <div class="bulletin--card__dummy"></div>
most class names do not follow BEM naming convention.

2022-08-11 10:18 UTC, mattwang44 commented
I prefer merging this PR first. Let's deal with BEM in another PR

2022-08-11 10:18 UTC, merged