feat(tickets): add sponsorship pass content
pycontw/pycontw-frontend pull request #298
Opened 2022-07-23 08:03 UTC by tyuchx

## Types of changes

* **New feature**

## Description

Add Sponsorship pass content

## Expected behavior

![CleanShot 2022-07-23 at 15 11 35](https://user-images.githubusercontent.com/6921552/180596350-1b1a8445-d179-49e5-b242-672955d2c4cd.png)

![CleanShot 2022-07-23 at 15 11 49](https://user-images.githubusercontent.com/6921552/180596359-db64a787-403c-4ff3-861c-898fb9fcd888.png)

2022-07-23 09:00 UTC, mattwang44 requested changes
plz rebase to latest main branch

2022-07-23 13:28 UTC, tyuchx commented
@josix @mattwang44 @uranusjr plz help review

2022-07-23 15:43 UTC, mattwang44 reviewed
Should add spaces

2022-07-23 15:43 UTC, mattwang44 commented on i18n/registration/tickets.i18n.js
> +            'Young Inspirers(where young and promising students can share their unique Python ' +
```suggestion
            'Young Inspirers (where young and promising students can share their unique Python ' +
```

2022-07-23 15:43 UTC, mattwang44 commented on i18n/registration/tickets.i18n.js
> +            'and events over the past decade, namely PyCon APAC 2022(the main conference), ' +
```suggestion
            'and events over the past decade, namely PyCon APAC 2022 (the main conference), ' +
```

2022-07-23 15:43 UTC, mattwang44 commented on i18n/registration/tickets.i18n.js
> +            'Sprints, Job Fair, Open Space, PyNight, PyCast(PyCon TW’s podcast), and ' +
```suggestion
            'Sprints, Job Fair, Open Space, PyNight, PyCast (PyCon TW’s podcast), and ' +
```

2022-07-23 15:44 UTC, mattwang44 approved these changes
英文讀起來還是有點尷尬XD
不過就先這樣好了

2022-07-24 05:24 UTC, tyuchx commented
英文已經找 找人大改兩次了🥲

2022-07-24 05:24 UTC, tyuchx commented
英文已經找 找人大改兩次了🥲.

2022-07-24 06:16 UTC, mattwang44 commented on i18n/registration/tickets.i18n.js
> +            'PyCon TW Podcast - Pycast、獨特 Python 經歷的學生分享 - Young Inspirers ，' +
大小寫是不是這樣？
```suggestion
            'PyCon TW Podcast - PyCast、獨特 Python 經歷的學生分享 - Young Inspirers ，' +
```

2022-07-24 06:55 UTC, tyuchx commented on i18n/registration/tickets.i18n.js
> +            'PyCon TW Podcast - Pycast、獨特 Python 經歷的學生分享 - Young Inspirers ，' +
對 XD 被發現 typo 了

2022-07-24 06:57 UTC, tyuchx commented
順手修改了其他地方 PyCast 的 typo

2022-07-24 16:34 UTC, merged