[343] feat: update landing page into 2023
pycontw/pycontw-frontend pull request #353
Opened 2022-12-08 10:32 UTC by yungshenglu

## Types of changes

* **New feature**

## Description

- Update our landing page into 2023 designs
- [Desktop](https://www.figma.com/file/W3hdepQ7v7ZGYRP6QctBXH/PyCon-Taiwan-%E5%AE%98%E7%B6%B2%E8%A6%96%E8%A6%BA-2022?node-id=5132%3A45173&t=W0YV315qZnD8bftU-0)
- [Mobile](https://www.figma.com/file/W3hdepQ7v7ZGYRP6QctBXH/PyCon-Taiwan-%E5%AE%98%E7%B6%B2%E8%A6%96%E8%A6%BA-2022?node-id=5132%3A40172&t=W0YV315qZnD8bftU-0)

## Expected behavior

https://user-images.githubusercontent.com/11289171/207521035-5897dec8-c817-4729-bb72-734e3df77147.mov

## Related Issue
#343 

## Additional context
NA

2022-12-08 17:58 UTC, josix commented
@yungshenglu It appears that there is a conflict with the configuration for displaying buttons on the index page (reference #351). Could you please help to investigate and resolve the issue?

2022-12-08 18:20 UTC, josix requested changes
Thanks @yungshenglu, I've left some primary issues first. PTAL

2022-12-08 18:20 UTC, josix commented on pages/index.vue
> +        background-size: 60%;
**issue (blocking):** looks like the title image is not displaying correctly on my devices with screen resolutions of 1920x1080 and 1080x800, as shown in the following images.

**1920x1080**
![image](https://user-images.githubusercontent.com/18432820/206531818-d93ccb4a-a10d-441b-85c6-d5321f4681f9.png)

**1080x800**
<img width="693" alt="image" src="https://user-images.githubusercontent.com/18432820/206531578-d74ef9f5-69b2-43f6-aefa-d8d3b2619f6a.png">

2022-12-08 18:20 UTC, josix commented on config/pageLanding.js
> +export const landingButtonConfig = {
**praise:** Niiice extraction!

2022-12-14 16:49 UTC, josix requested changes
nit. I guess the following section could be removed, WDYT?
```js
        isCallingForProposals() {
            return this.$store.state.configs.showSpeakingPage
        },
        isShowingScheduleButton() {
            return this.$store.state.configs.showSchedulePage
        },
        showIndexSponsorSection() {
            return this.$store.state.configs.showIndexSponsorSection
        },
        showIndexAPACSection() {
            return this.$store.state.configs.showIndexAPACSection
        },
```

2022-12-14 16:50 UTC, josix approved these changes

2022-12-15 02:21 UTC, yungshenglu commented
> ```js
> isCallingForProposals
> ```

I need to check

2022-12-15 03:27 UTC, anan0202 commented
Web banner png and svg file has already been update. You can find the "Website banner" in the link below. Thank you very much. You are the best engineer!

https://drive.google.com/drive/u/0/folders/1bx-JsEhpnkfo85JD-cSvk4Swe6_5XgtO

2022-12-21 02:52 UTC, yungshenglu commented
> Web banner png and svg file has already been update. You can find the "Website banner" in the link below. Thank you very much. You are the best engineer!
> 
> https://drive.google.com/drive/u/0/folders/1bx-JsEhpnkfo85JD-cSvk4Swe6_5XgtO

Updated.

2022-12-21 04:59 UTC, josix approved these changes
LGTM!

2022-12-21 05:02 UTC, anan0202 approved these changes
Awesome! 太 Awesome 拉！

2022-12-21 05:02 UTC, merged