[#376] feat: 購票說明頁面
pycontw/pycontw-frontend pull request #390
Opened 2023-03-27 11:13 UTC by yungshenglu

## Types of changes
* **New feature**

## Description
- 購票說明頁面

## Steps to Test This Pull Request
1. Path: `/2023/zh-hant/registration/tickets` & `2023/en-us/registration/tickets`
2. Check the description of "購票說明 / Tickets" both zh-hant and English.

## Screenshots

https://user-images.githubusercontent.com/11289171/227925724-26cb305b-99d3-44af-9a5f-cc0b1c7a79e0.mov

## Related Issue
#376 

## Additional context
- Spec: https://docs.google.com/document/d/12VtFMOZD3DNMxGmhPXM24ZYxhGdK1fELNuUNGouCGNw/edit?usp=sharing
- Design: https://www.figma.com/file/W3hdepQ7v7ZGYRP6QctBXH/PyCon-Taiwan-%E5%AE%98%E7%B6%B2%E8%A6%96%E8%A6%BA-2022?node-id=5339-24303&t=LRYq1oyPspEVqoHj-0

2023-03-29 12:24 UTC, yungshenglu commented on pages/registration/tickets.vue
> +                    class="mx-4 text-[40px]"
Thanks for your suggestion. I've already updated, please check.

2023-03-31 05:51 UTC, josix requested changes

2023-03-31 05:51 UTC, josix commented on i18n/registration/tickets.i18n.js
**praise:** Nice! The structure would make the entity more clear!

2023-03-31 05:51 UTC, josix commented on pages/registration/tickets.vue
> +                                }}</locale-link>
**issue (blocking):** 
```suggestion
                               <locale-link
                                    :to="pageLinks.financialAid"
                                    underline
                                    highlight
                                    >{{ $t('terms.financialAid') }}
                                </locale-link>
```

2023-03-31 05:51 UTC, josix commented on pages/registration/tickets.vue
> +                        }}</locale-link>
**issue (blocking):** 
```suggestion
                               <locale-link
                                    :to="pageLinks.financialAid"
                                    underline
                                    highlight
                                    >{{ $t('terms.financialAid') }}
                                </locale-link>
```

2023-03-31 05:54 UTC, josix requested changes

2023-03-31 05:54 UTC, josix commented on i18n/registration/tickets.i18n.js
> +                    title: '您有需要財務補助嗎？ (尚未開放，敬請期待)',
**issue (blocking):** 
```suggestion
                    title: '您有需要財務補助嗎？',
```

2023-03-31 05:54 UTC, josix commented on i18n/registration/tickets.i18n.js
> +                    title: 'Need Financial Aid? (Coming Soon.)',
**issue (blocking):** 
```suggestion
                    title: 'Need Financial Aid?',
```

2023-03-31 07:40 UTC, yungshenglu commented on i18n/registration/tickets.i18n.js
> +                    title: '您有需要財務補助嗎？ (尚未開放，敬請期待)',
Fixed.

2023-03-31 07:40 UTC, yungshenglu commented on i18n/registration/tickets.i18n.js
> +                    title: 'Need Financial Aid? (Coming Soon.)',
Fixed.

2023-03-31 07:40 UTC, yungshenglu commented on pages/registration/tickets.vue
> +                        }}</locale-link>
Fixed.

2023-03-31 07:40 UTC, yungshenglu commented on pages/registration/tickets.vue
> +                                }}</locale-link>
Fixed.

2023-03-31 08:38 UTC, josix approved these changes
LGTM!

2023-03-31 08:38 UTC, merged