feat - add custom layout for staff page
pycontw/pycontw-frontend pull request #425
Opened 2023-07-18 13:47 UTC by SivanYeh

add a custom layout to hide footer and header at page staff, switch the layout based on CCIP token

2023-07-18 13:51 UTC, SivanYeh commented
Gotta figure out how to switch the layout with token, and which CCIP token meant to be the key.
Almost there!

2023-07-24 18:12 UTC, josix requested changes

2023-07-24 18:27 UTC, mattwang44 commented on layouts/ccip.vue
> +            meta: [
`meta` & `script` 內的設定大多是為了有更好的 SEO，但這個特製的 layout 在我想像中不需要這些設定、甚至不希望只會使用這個 layout 的頁面會在搜尋引擎上被搜尋到

2023-07-24 18:29 UTC, mattwang44 commented on layouts/ccip.vue
> +            <Nuxt keep-alive :keep-alive-props="{ include: includeArr }" />
keep alive 是為了時間表頁面所做的特殊設定 (see #299)，CCIP 頁面不會需要

2023-08-06 10:36 UTC, SivanYeh commented on pages/about/staff.vue
> +            isAppMode: false,
Oh mine. It was a deprecated parameter. I will delete it!

2023-08-06 11:01 UTC, SivanYeh commented on layouts/ccip.vue
> +            meta: [
Deleted!

2023-08-06 11:23 UTC, SivanYeh commented on layouts/ccip.vue
> +            <Nuxt keep-alive :keep-alive-props="{ include: includeArr }" />
Done!

2023-08-16 12:26 UTC, yungshenglu commented on pages/about/staff.vue
> +        return 'default'
Minor: prefer to use `? :`
```
return ccip ? 'ccip' : 'default';
```

2023-08-17 06:35 UTC, mattwang44 approved these changes
LGTM
Please modify the PR based on David's comments.

2023-08-19 09:47 UTC, SivanYeh commented on pages/about/staff.vue
> +        return 'default'
原來是這樣用!

2023-08-19 09:58 UTC, SivanYeh commented on layouts/ccip.vue
> +    box-sizing: border-box;
好建議! 不過我的tailwind還不夠純熟. 先維持這樣. 之後再開一個PR改語法

2023-08-24 06:38 UTC, yungshenglu approved these changes
LGTM

2023-08-26 04:04 UTC, josix approved these changes

2023-08-26 04:04 UTC, merged