Feat(reg/tickets): update content to 2024 in ticket page
pycontw/pycontw-frontend pull request #535
Opened 2024-06-04 05:46 UTC by SivanYeh

## Types of changes

* **New feature**

## Description

Release 2024 Ticket Info 

## Steps to Test This Pull Request

1. Go to “http://localhost:3000/2024/zh-hant/registration/tickets"
2. Check if content has been updated and matched the document: https://docs.google.com/document/d/1fqyk_UEdX1k44xjHzUGevWDQ8PgsIQ9_T32DmTQ_bRw/edit.
3. Repeat step 1-2 for english version “http://localhost:3000/2024/en-us/registration/tickets”

## Related Issue

#523

## Screenshot
<img width="482" alt="image" src="https://github.com/pycontw/pycontw-frontend/assets/26858727/0d9f9373-2543-4bf6-9700-4ab15de257b9">

2024-06-05 13:54 UTC, rockleona requested changes
Review 1st Round!

2024-06-05 13:54 UTC, rockleona commented on configs/pageTickets.js
這邊的 KKTIX 連結 (value) 都沒有更新到ㄟ

2024-06-05 13:54 UTC, rockleona commented on configs/pageTickets.js
> +                price: 'NT$ 5,222',
```suggestion
                price: 'NT$ 5,220',
```

2024-06-06 02:36 UTC, SivanYeh commented
@rockleona fixed! 感謝挑錯!!

2024-06-06 13:42 UTC, rockleona approved these changes
LGTM! 可能要提醒下一個階段處理這個頁面的志工留意一下有關 KKTIX 的連結

2024-06-09 02:14 UTC, merged