feat: open space
pycontw/pycontw-frontend pull request #556
Opened 2024-07-16 13:25 UTC by Ritabear

## Types of changes
- open the page of the open space
- open space i18n

## Related Issue
[#532](https://github.com/pycontw/pycontw-frontend/issues/532)

2024-07-22 15:03 UTC, SivanYeh commented
文案上週有更新一版：https://docs.google.com/document/d/1WHCKUe2zYoG88bPHJfsvYm7doN7XcoeUkBuGDR5xt8w/edit

我把更新的部分標註下

2024-07-22 15:04 UTC, SivanYeh commented on i18n/events/open-spaces.i18n.js
> +            'Open Spaces are self-organizing meetup events that occur simultaneously with the main conference. ' +
-> "Open Space is a self-organizing meetup event that occurs simultaneously with the main conference."

2024-07-22 15:05 UTC, SivanYeh commented on i18n/events/open-spaces.i18n.js
> +            'Organized by attendees during PyCon Taiwan, Open Spaces allow you to define, organize, ' +
-> "Open Space allows you to define, organize"

2024-07-22 15:07 UTC, SivanYeh commented on i18n/events/open-spaces.i18n.js
> +            'For those who have participated in past PyCon Taiwan or other conferences, ' +
"For those who..."前加斷行

2024-07-27 14:14 UTC, SivanYeh requested changes
@Ritabear 最後一哩路了：
1. 把剩下4條我還沒刪除或resolve的comments 修改完成
2. 到codebase查詢任何複數型Open Spaces, 將它改成單數. 例如：NavBar.i18n.js裡面的Open Spaces
<img width="482" alt="image" src="https://github.com/user-attachments/assets/0b62795f-6923-47b5-a887-ab007f6c2ccc">

2024-07-27 14:14 UTC, SivanYeh commented on i18n/events/open-spaces.i18n.js
> +                    'Main Session: Day 2, 14:40–15:40' +
斷行-> "Main Session: Day 2, 14:40–15:40{br}"

2024-07-27 14:14 UTC, SivanYeh commented on i18n/events/open-spaces.i18n.js
>                      'We don’t know either! It’s up to you and fellow attendees 😉{br}' +
句號-> 'We don’t know either! It’s up to you and fellow attendees. 😉{br}'

2024-07-27 14:14 UTC, SivanYeh commented on i18n/events/open-spaces.i18n.js
>              'Open Spaces are self-organizing meetup events that happen simultaneously with the main conference. ' +
-> 'Open Space is ...'

2024-08-14 04:22 UTC, mattwang44 approved these changes

2024-08-15 09:10 UTC, merged